language: node_js
node_js:
  - 10
  - 12
  - 14
deploy:
  - provider: script
    script: npx nlm release
    skip_cleanup: true
    'on':
      branch: main
      node: 14
env:
  - CXX=g++-4.8
addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
